package io.github.mizar107.zapegruntime.servant;

import java.util.Optional;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.Vec3;

/** Deterministic, loaded-chunk-only placement policy for Servants. */
public final class ServantSpawnPolicy {

    private static final int[][] HORIZONTAL_OFFSETS = {
        {0, 0}, {1, 0}, {-1, 0}, {0, 1}, {0, -1},
        {2, 0}, {-2, 0}, {0, 2}, {0, -2}, {1, 1}, {-1, -1}, {1, -1}, {-1, 1}
    };
    private static final int[] VERTICAL_OFFSETS = {0, 1, -1, 2, -2};

    private ServantSpawnPolicy() {}

    /**
     * Moves {@code servant} to the first safe candidate and returns its feet
     * position. No chunks are loaded or generated by this method.
     */
    public static Optional<BlockPos> placeSafely(
            ServerLevel level,
            HeraldorServant servant,
            ServerPlayer target) {
        Vec3 look = target.getLookAngle();
        double horizontalLength = Math.sqrt(look.x * look.x + look.z * look.z);
        double directionX = horizontalLength < 0.001D ? 0.0D : look.x / horizontalLength;
        double directionZ = horizontalLength < 0.001D ? 1.0D : look.z / horizontalLength;
        double spawnDistance = servant.archetype().spawnDistance();
        Vec3 base = target.position().subtract(
                directionX * spawnDistance,
                0.0D,
                directionZ * spawnDistance);
        int baseX = (int) Math.floor(base.x);
        int baseY = (int) Math.floor(target.getY());
        int baseZ = (int) Math.floor(base.z);

        for (int yOffset : VERTICAL_OFFSETS) {
            for (int[] offset : HORIZONTAL_OFFSETS) {
                BlockPos feet = new BlockPos(
                        baseX + offset[0],
                        baseY + yOffset,
                        baseZ + offset[1]);
                if (!loadedAndInsideBuildHeight(level, feet)) {
                    continue;
                }

                BlockPos floor = feet.below();
                BlockState floorState = level.getBlockState(floor);
                boolean clear = hasThreeBlockClearance(level, feet);
                servant.moveTo(
                        feet.getX() + 0.5D,
                        feet.getY(),
                        feet.getZ() + 0.5D,
                        target.getYRot() + 180.0F,
                        0.0F);
                boolean collisionChunksLoaded = ServantLoadedChunks.areaLoaded(
                        level, servant.getBoundingBox().inflate(0.01D));
                CandidateFacts facts = new CandidateFacts(
                        floorState.isFaceSturdy(level, floor, Direction.UP),
                        isHazardous(floorState),
                        clear,
                        clear && hasNoFluid(level, feet),
                        level.getWorldBorder().isWithinBounds(servant.getBoundingBox()),
                        collisionChunksLoaded && level.noCollision(servant),
                        true,
                        collisionChunksLoaded);
                if (isSafe(facts)) {
                    return Optional.of(feet);
                }
            }
        }
        return Optional.empty();
    }

    public static boolean isSafe(CandidateFacts facts) {
        return facts.floorSturdy()
                && !facts.floorHazardous()
                && facts.threeBlockClearance()
                && facts.noFluid()
                && facts.insideWorldBorder()
                && facts.noCollision()
                && facts.insideBuildHeight()
                && facts.chunkAlreadyLoaded();
    }

    private static boolean loadedAndInsideBuildHeight(ServerLevel level, BlockPos feet) {
        if (feet.getY() <= level.getMinBuildHeight()
                || feet.getY() + 2 >= level.getMaxBuildHeight()) {
            return false;
        }
        return ServantLoadedChunks.blockColumnLoaded(level, feet)
                && ServantLoadedChunks.spawnProbeLoaded(level, feet);
    }

    private static boolean hasThreeBlockClearance(ServerLevel level, BlockPos feet) {
        for (int offset = 0; offset < 3; offset++) {
            BlockPos position = feet.above(offset);
            BlockState state = level.getBlockState(position);
            if (!state.getCollisionShape(level, position).isEmpty() || isHazardous(state)) {
                return false;
            }
        }
        return true;
    }

    private static boolean hasNoFluid(ServerLevel level, BlockPos feet) {
        for (int offset = 0; offset < 3; offset++) {
            if (!level.getFluidState(feet.above(offset)).isEmpty()) {
                return false;
            }
        }
        return level.getFluidState(feet.below()).isEmpty();
    }

    private static boolean isHazardous(BlockState state) {
        return state.is(Blocks.CACTUS)
                || state.is(Blocks.MAGMA_BLOCK)
                || state.is(Blocks.CAMPFIRE)
                || state.is(Blocks.SOUL_CAMPFIRE)
                || state.is(Blocks.FIRE)
                || state.is(Blocks.SOUL_FIRE)
                || state.is(Blocks.LAVA)
                || state.is(Blocks.POWDER_SNOW)
                || state.is(Blocks.SWEET_BERRY_BUSH)
                || state.is(Blocks.WITHER_ROSE)
                || state.is(Blocks.POINTED_DRIPSTONE);
    }

    public record CandidateFacts(
            boolean floorSturdy,
            boolean floorHazardous,
            boolean threeBlockClearance,
            boolean noFluid,
            boolean insideWorldBorder,
            boolean noCollision,
            boolean insideBuildHeight,
            boolean chunkAlreadyLoaded) {}
}
